[database]
max_connections = 5

[rpc]
url = "https://mainnet.helius-rpc.com/?api-key="
rps = 8
max_concurrent = 2
max_rate_limit_retries = 4

[server]
bind = "0.0.0.0:8080"
cors_allowed_origins = ["http://127.0.0.1:5500"]

[workers]
count = 4

[logging]
level = "info"
dir = "logs/"
